# Generated by Django 4.2.5 on 2023-11-26 06:10

from django.db import migrations, models
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True)),
            ],
        ),
    ]
