# Generated by Django 4.2.5 on 2023-09-23 20:29

from django.db import migrations, models
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0002_developer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True)),
                ('user', models.ManyToManyField(to='register.developer')),
            ],
        ),
    ]
