# Generated by Django 4.2.5 on 2023-11-28 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_message_delete_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumn',
            name='title',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
