# Generated by Django 4.2.5 on 2024-01-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_curriculumn_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumn',
            name='lastupdated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
