# Generated by Django 4.2.5 on 2024-01-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_curriculumn_lastupdated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumn',
            name='lastupdated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
