# Generated by Django 4.2.5 on 2024-01-01 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_curriculumn_lastupdated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculumn',
            name='lastupdated',
        ),
        migrations.RemoveField(
            model_name='curriculumn',
            name='title',
        ),
    ]
